format = 2

[[dependency]]
name = "AudioLibSwitcher"
github = "razterizer/AudioLibSwitcher"
package = "AudioLibSwitcher"
version = "1.0.0+build.1"
target = "any"
url = "https://github.com/razterizer/AudioLibSwitcher/releases/download/release-1.0.0.1/AudioLibSwitcher-1.0.0+build.1-ho.cbox"
sha256 = "1212374681c81168d3c4aced82a6737b5885cea06710e9abb640e380cccbf3ea"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "linux-x86_64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-linux-x86_64.cbox"
sha256 = "6deee8b61f6600259dbd11de8641dda59577b9ea295604117f60cabacdb3896f"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "macos-arm64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-macos-arm64.cbox"
sha256 = "bb2b0298b6e6ae1609bd2b1ac20b40d7efa9758f511d6d43b1899cd83acf8ca4"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "windows-x86_64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-windows-x86_64.cbox"
sha256 = "430e9b819ff5689cfce801c9d1daa129eb2173d598a8dd351c01b93f69d2b725"
