format = 2

[[dependency]]
name = "AudioLibSwitcher"
github = "razterizer/AudioLibSwitcher"
package = "AudioLibSwitcher"
version = "1.0.0+build.1"
target = "any"
url = "https://github.com/razterizer/AudioLibSwitcher/releases/download/release-1.0.0.1/AudioLibSwitcher-1.0.0+build.1-ho.cbox"
sha256 = "1212374681c81168d3c4aced82a6737b5885cea06710e9abb640e380cccbf3ea"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "linux-x86_64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-linux-x86_64.cbox"
sha256 = "e66fb5e6a579791dd2a318c7253b1ebba7379c0c8403fbc5ca536f678ad04fd0"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "macos-arm64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-macos-arm64.cbox"
sha256 = "d511797dc95294deb97d7ed7f5bf17b7a11d71ad8c074a1aba4e3601f53ece31"

[[dependency]]
name = "applaudio"
github = "razterizer/applaudio"
package = "applaudio"
version = "1.0.1+build.4"
target = "windows-x86_64"
url = "https://github.com/razterizer/applaudio/releases/download/release-1.0.1.4/applaudio-1.0.1+build.4-windows-x86_64.cbox"
sha256 = "edf2e3b7e804341c3652b0436ea4564af25d0432d736c1dccbab16803cde9d7b"
