#:schema https://raw.githubusercontent.com/razterizer/forge/main/schemas/forge.recipe.schema.json

[project]
name = "AudioLibSwitcher_applaudio"
version = "1.0.0"
type = "header_only"
cpp_std = 20

[sources]
paths = []
public_headers = ["include/AudioLibSwitcher/AudioLibSwitcher_applaudio.h"]
include_dirs = ["include"]

[build]
number = 2

[release]
build_number_format = "dotted"

[dependencies]
AudioLibSwitcher = { path = "AudioLibSwitcher" }
applaudio = { path = "../applaudio" }

[profile.workflow-release.dependencies]
AudioLibSwitcher = { github = "razterizer/AudioLibSwitcher", version = "1.0.0+build.1" }
applaudio = { github = "razterizer/applaudio", version = "1.0.0+build.2" }

[profile.workflow-release.build]
configuration = "Release"

[profile.Debug.build]
configuration = "Debug"
defines = ["DEBUG=1"]

[profile.Release.build]
configuration = "Release"
